### PR TITLE
Development

### PR DESCRIPTION
**Pull request by txubelaxu**

### CODE REVIEW

**Comment by Sleeper85** [comment]
@txubelaxu 

If you want to collaborate please copy the `development` branch in your fork into two other branches. One synchronized branch reserved for PRs (adding features, fixing bugs) and another branch for your testing and personal development.

I will soon release YamBMS version `1.4.3` with `Victron and Junctek shunt` support and other new features.

When you make a PR, all the changes you made on your side are sent to me. 
Some changes are purely personal.
I'm sorry but I will have to decline your PR.

**Comment by txubelaxu** [comment]
Yes, of course. Sorry because I am newbie at github...
So, If I have understand correctly, I need a total of 3 branches in my
fork? For example:
- development
- development_pr
- development_txubelaxu

Sorry again and many thanks!!

**Comment by Sleeper85** [comment]
> Yes, of course. Sorry because I am newbie at github...
So, If I have understand correctly, I need a total of 3 branches in my
fork? For example:

Only two :
- development ( for PR and stays in sync )
- development_txubelaxu ( for You )

Soon I will move this project to its [new dedicated git](https://github.com/Sleeper85/esphome-yambms).

**Comment by txubelaxu** [comment]
OK

**Pull request closed without merging**
