### PR TITLE
Revert "Adding Configuration Clarification in Atom S3 Config File"

### PR DESCRIPTION
**Pull request by Sleeper85**
Reverts Sleeper85/esphome-jk-bms-can#36

### CODE REVIEW

**Comment by luckylinux** [comment]
May I ask why ? I thought the explanation in the config file were an improvement.

**Comment by Sleeper85** [comment]
Yes it is a clarification but also a confusion with the GPIOs for the JK-BMS UART.

In your case, you can only use the Bluetooth version?

**Comment by luckylinux** [comment]
> Yes it is a clarification but also a confusion with the GPIOs for the JK-BMS UART.
> 
> In your case, you can only use the Bluetooth version?

Well everything is possible, but right now I have installed the JK BMS RS485 "Converter" and ended it on terminal blocks.

Fact of the matter is, unless I stop the system and start tinking with the battery, I cannot wire it up. I don't really want to go in that section of the cabinet when the battery is live ...

**Comment by Sleeper85** [comment]
Even if the CAN bus adapter you purchased is compatible. This is not the one we recommend using (question of simplicity). In the future packaged version there will be YAML for Atom S3 Lite / Display and ATOMIC CANBus Base (CA-IS3050G) - SKU: A103 is the base used by default. GPIOs 1 and 2 are those reserved for the UART JK-BMS connection. I just don't want to add even more complexity. I hope you understand my decision.

**Pull request closed without merging**
